### ISSUE TITLE
NoClassDefFoundError: org/jetbrains/kotlin/preprocessor/PreprocessorKt

### ISSUE THREAD

**Issue by KristofVanDaele** [icapps/android_gradle_build#19]
Create new project, add only gradle plugin with only detekt in it.

```
iCappsBuildConfig {
     detekt {
     }
}
```

This fails with the following error during gradle sync.
`Caused by: java.lang.NoClassDefFoundError: org/jetbrains/kotlin/preprocessor/PreprocessorKt`

@vanlooverenkoen  thinks this line is the issue in detektCheck
`file.parentFile.mkdirsOrFail()`

If I remove detekt from the iCappsBuildConfig, it syncs just fine.

**Comment by vanlooverenkoen** [comment]
Should be fixed with the new release `1.0.14`

**Comment by vanlooverenkoen** [comment]
@KristofVanDaele can you confirm otherwise reopen.
