### ISSUE TITLE
401 Failed to get list of languages

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/android_gradle_build#20]
401 Failed to get list of languages

Languages cannot be fetched. Issue with -> https://github.com/Chimerapps/icapps-translations-gradle-plugin ??

**Comment by vanlooverenkoen** [comment]
Related issue: 
https://github.com/Chimerapps/icapps-translations-gradle-plugin/issues/4

**Comment by NicolaVerbeeck** [comment]
Chimerapps/icapps-translations-gradle-plugin#4 Closed and version 1.0.5 is released

**Comment by vanlooverenkoen** [comment]
Updated the plugin to 1.0.5 
This Pull Request should fix it: #21

**Comment by vanlooverenkoen** [comment]
Should be fixed with the new release `1.0.14`
