### ISSUE TITLE
Does not work on libraries. Log as error

### ISSUE THREAD

**Issue by KristofVanDaele** [icapps/android_gradle_build#24]
https://github.com/icapps/android_gradle_build/blob/a86425821e2b8cd6d3a2bbedea1874eb5229beb5/src/main/java/com/icapps/build/gradle/plugin/BuildPlugin.kt#L31

**Comment by KristofVanDaele** [comment]
Update the gradle plugin so the detekt will be enabled for libraries

**Comment by vanlooverenkoen** [comment]
fixed in version 1.0.15
